Added AfterPay countries available.
emspay/ems-online-woocommerce pull request #21
Opened 2020-07-20 11:58 UTC by LeasoftKonstantinShapoval

2020-07-28 15:15 UTC, tiutiunnykleasoft requested changes
Error on the checkout page

2020-07-28 15:15 UTC, tiutiunnykleasoft commented on emspay.php
> +            if (!in_array(WC()->customer->billing['country'], $countrylist)) {
![изображение](https://user-images.githubusercontent.com/60009163/88685027-2f2d7400-d0fe-11ea-9c2b-0b9913686a80.png)

2020-08-13 14:31 UTC, LeasoftKonstantinShapoval commented on emspay.php
> +            if (!in_array(WC()->customer->billing['country'], $countrylist)) {
This errors is not for my side. Check server settings, all install requires and follow install order. Checked by new clear WP site.

2020-08-17 10:38 UTC, tiutiunnykleasoft commented on emspay.php
> +            if (!in_array(WC()->customer->billing['country'], $countrylist)) {
@LeasoftKonstantinShapoval  : What version wooCommerce you are using ?

2020-08-19 15:37 UTC, tiutiunnykleasoft approved these changes
Ok.

2020-09-07 14:37 UTC, merged